Add missing AWS components
aws-observability/aws-otel-collector pull request #1590
Opened 2022-10-26 17:42 UTC by awsimaya

**Description:** Added missing AWS components in the README.md file

**Link to tracking Issue:** None

**Testing:** Only a document change. No code changes. Hence no testing was performed.

**Documentation:** Added missing AWS components in the README.md file 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-10-26 17:46 UTC, mhausenblas approved these changes

2022-10-26 17:50 UTC, bryan-aguilar requested changes
`ecstaskobserver` is not currently bundled in the ADOT Distribution. Bundled components can be found [here](https://github.com/aws-observability/aws-otel-collector/blob/main/pkg/defaultcomponents/defaults.go).

2022-10-27 02:23 UTC, awsimaya commented
Made a new commit removing the ECS Task Observer. Check it out.

2022-10-27 02:48 UTC, bryan-aguilar approved these changes

2022-10-27 02:48 UTC, merged